networks:
  network:
    name: network_${NAME_PROJECT}

services:
  nginx:
    container_name: nginx_${NAME_PROJECT}
    image: nginx
    ports:
      - 80:80
    volumes:
#      - ./vhost.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/templates/:/etc/nginx/templates
      - ./www:/etc/nginx/html
    networks:
      - network
    depends_on:
      - php
      - mysql
    env_file:
      - ./.env
  php:
    container_name: php_${NAME_PROJECT}
    build: ./images/php
    volumes:
      - ./www:/etc/nginx/html
    networks:
      - network
    depends_on:
      - mysql
  mysql:
    container_name: mysql_${NAME_PROJECT}
    image: mysql
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - network

  phpmyadmin:
    container_name: phpmyadmin_${NAME_PROJECT}
    image: phpmyadmin
    ports:
      - 8000:80
    environment:
      - PMA_HOST=mysql
    networks:
      - network
    depends_on:
      - mysql